/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INGREDIENTS = 1;
  /** RegularExpression Id. */
  int MEASURE_TYPE = 2;
  /** RegularExpression Id. */
  int DRY_MEASURE = 3;
  /** RegularExpression Id. */
  int WET_MEASURE = 4;
  /** RegularExpression Id. */
  int UNSPECIFIED_MEASURE = 5;
  /** RegularExpression Id. */
  int COOKING_TIME = 6;
  /** RegularExpression Id. */
  int TIME_UNIT = 7;
  /** RegularExpression Id. */
  int PREHEAT = 8;
  /** RegularExpression Id. */
  int TEMP_UNIT = 9;
  /** RegularExpression Id. */
  int GAS_MARK = 10;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 11;
  /** RegularExpression Id. */
  int METHOD = 12;
  /** RegularExpression Id. */
  int TAKE = 13;
  /** RegularExpression Id. */
  int PUT = 14;
  /** RegularExpression Id. */
  int FROM = 15;
  /** RegularExpression Id. */
  int INTO = 16;
  /** RegularExpression Id. */
  int TO = 17;
  /** RegularExpression Id. */
  int THE = 18;
  /** RegularExpression Id. */
  int FRIDGE = 19;
  /** RegularExpression Id. */
  int MIXING_BOWL = 20;
  /** RegularExpression Id. */
  int NUMBER = 21;
  /** RegularExpression Id. */
  int FULLSTOP = 22;
  /** RegularExpression Id. */
  int CHAR = 23;
  /** RegularExpression Id. */
  int EOL = 24;
  /** RegularExpression Id. */
  int SPACE = 25;

  /** Lexical state. */
  int INGREDIENTS_STATE = 0;
  /** Lexical state. */
  int COOKING_TIME_STATE = 1;
  /** Lexical state. */
  int OVEN_TEMP_STATE = 2;
  /** Lexical state. */
  int METHOD_STATE = 3;
  /** Lexical state. */
  int DEFAULT = 4;
  /** Lexical state. */
  int COMMENTS_STATE = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"Ingredients\"",
    "<MEASURE_TYPE>",
    "<DRY_MEASURE>",
    "<WET_MEASURE>",
    "<UNSPECIFIED_MEASURE>",
    "<COOKING_TIME>",
    "<TIME_UNIT>",
    "<PREHEAT>",
    "<TEMP_UNIT>",
    "<GAS_MARK>",
    "\")\"",
    "\"Method.\"",
    "\"Take\"",
    "\"Put\"",
    "\"from\"",
    "\"into\"",
    "\"to\"",
    "\"the\"",
    "\"refrigerator\"",
    "<MIXING_BOWL>",
    "<NUMBER>",
    "\".\"",
    "<CHAR>",
    "<EOL>",
    "<SPACE>",
  };

}
